### ISSUE TITLE
Tests are not runable

### ISSUE THREAD

**Issue by blakecaldwell** [jasmainak/mne-neuron#53]
It's very cool that results can be compared to HNN on new commits. However, a couple of issues running the tests locally

1. Tests should probably not depend on mne:
```
========================================================= ERRORS =========================================================
_________________________________ ERROR collecting mne_neuron/tests/test_compare_hnn.py __________________________________
ImportError while importing test module '/Users/blake/repos/mne-neuron-new/mne_neuron/tests/test_compare_hnn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
mne_neuron/tests/test_compare_hnn.py:6: in <module>
    from mne.utils import _fetch_file
E   ModuleNotFoundError: No module named 'mne'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================ 1 error in 0.37 seconds =================================================
```
2. Where is /test_data/ (forgive my ignorance of travis CI)?
https://github.com/jasmainak/mne-neuron/blob/master/mne_neuron/tests/test_compare_hnn.py#L16

**Comment by jasmainak** [comment]
1. We need MNE for the automatic fetcher. I agree it's probably an overkill as we could use `urllib` as well.

2. The test data is on another "bare" branch which does not have the history of master. Here: https://raw.githubusercontent.com/jasmainak/mne-neuron/test_data/dpl.txt. It's a cheap solution for now. We can make something more sophisticated later.
