### ISSUE TITLE
Procedure for building docs

### ISSUE THREAD

**Issue by blakecaldwell** [jasmainak/mne-neuron#54]
So when trying to run Sphinx Gallery I get an error that is easy to understand. However, I feel that I'm probably missing something in your workflow rather than `touch examples/README.txt`. Could you include more verbose instructions in CONTRIBUTING?
```
(hnn) Blakes-MacBook-Pro:doc blake$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v2.1.1
making output directory... done
generating gallery...

Exception occurred:
  File "/Users/blake/miniconda3/envs/hnn/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 262, in generate_gallery_rst
    .format(examples_dir))
FileNotFoundError: Main example directory /Users/blake/repos/mne-neuron-new/doc/../examples does not have a README.txt file. Please write one to introduce your gallery.
The full traceback has been saved in /var/folders/zq/5r57yxls19q2wcq98g5r4gb40000gn/T/sphinx-err-ikb8ajow.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

**Comment by jasmainak** [comment]
arggh ... sorry about that. This should be fixed. We should have a README.txt just as in [MNE](https://github.com/mne-tools/mne-python/blob/master/examples/forward/README.txt)

**Comment by blakecaldwell** [comment]
Another issue. 
```
(hnn) Blakes-MacBook-Pro:doc blake$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v2.1.1
generating gallery...
/Users/blake/miniconda3/envs/hnn/lib/python3.6/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())

Exception occurred:
  File "/Users/blake/miniconda3/envs/hnn/lib/python3.6/site-packages/sphinx_gallery/binder.py", line 253, in check_binder_conf
    'Did not find one of `requirements.txt` or `environment.yml` '
ValueError: Did not find one of `requirements.txt` or `environment.yml` in the "dependencies" section of the binder configuration for sphinx-gallery. A path to at least one of these files must exist in your Binder dependencies.
```

You have a fix merged in sphinx-gallery, but it would seem a Dockerfile needs to be created for mne-neuron?
https://github.com/sphinx-gallery/sphinx-gallery/issues/476

**Comment by jasmainak** [comment]
ah, you are having this issue because `sphinx-gallery` has not made a release since I made the fix. If you use the development version of `sphinx-gallery` you should not have the problem. I could update the contributing.md if you want but it would need to be updated again when `sphinx-gallery` makes their release

**Comment by jasmainak** [comment]
> Dockerfile needs to be created for mne-neuron?

This is only for the binder demo. I prefer not to force people to use docker images as much as possible.
